-- Historical migration marker.
--
-- The restrictive v3.3 migration was applied to production on 2026-08-08.
-- Its reviewed SQL is preserved at:
-- docs/archive/sql/20260808125353_v3_3_trust_foundations.applied.sql
--
-- A later production_schema_baseline migration contains the resulting secure
-- schema and is the canonical starting point for fresh environments.
